sudo: required
services:
  - docker

before_install:
  - docker build -t vladimirgruicic/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true vladimirgruicic/react-test npm test 

after_success:
  - docker build -t vladimirgruicic/multi-client ./client
  - docker build -t vladimirgruicic/multi-nginx ./nginx
  - docker build -t vladimirgruicic/multi-server ./server
  - docker build -t vladimirgruicic/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vladimirgruicic/multi-client
  - docker push vladimirgruicic/multi-nginx
  - docker push vladimirgruicic/multi-server
  - docker push vladimirgruicic/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-456582705970
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
